### ISSUE TITLE
cookie issue

### ISSUE THREAD

**Issue by lampi8426** [t-abraham/instagent#3]
![image](https://user-images.githubusercontent.com/74324159/204532627-1884fa15-5d9f-4615-b9a9-583900c7260a.png)

**Comment by ghostkernel-core** [comment]
Hi

I am aware of the issue. I didn't work on the current version as this one uses and API which is unmaintained and also doesn't not solve challenges or other issues

Please wait for a week or two for v2 release. In the next version of the release I am replacing the whole API which is well maintained and can handle these cookies as sessions and can handle challenges too as well as proxies if required

**Comment by ghostkernel-core** [comment]
Version 2.0 is publish where the cookie issue is solved
