### ISSUE TITLE
ModuleNotFoundError: No module named 'instagrapi'

### ISSUE THREAD

**Issue by Rayzen-dev** [t-abraham/instagent#6]
**Describe the bug**
```
Traceback (most recent call last):
  File "/home/tools/osint/instagent/./app/main.py", line 3, in <module>
    from src.instagent import instagent
  File "/home/tools/osint/instagent/app/src/instagent.py", line 12, in <module>
    from instagrapi import Client
ModuleNotFoundError: No module named 'instagrapi'
```

**To Reproduce**
1. git clone https://github.com/t-abraham/instagent.git
2. cd instagent
3. python3 -m venv venv
4. source ./venv/bin/activate
5. pip install -r ./app/requirements.txt
6. Setting up application
7. python3 ./app/main.py myTarget

**Expected behavior**
Have the console prompt to run commands.

**Desktop (please complete the following information):**
 - OS: Parrot

**Comment by ghostkernel-core** [comment]
Hello [Rayzen-dev](https://github.com/Rayzen-dev). Thank you for pointing out the issue. It was due to a missing module in the requirements file. I have just now updated the file... You can either re-download the system again and try or just update the requirements.txt file with the latest one and resume from step 5

**Comment by Rayzen-dev** [comment]
Hello, now this is this error: `ModuleNotFoundError: No module named 'PIL'`.

```
Traceback (most recent call last):
  File "/home/g0dzila/tools/osint/instagent/app/main.py", line 3, in <module>
    from src.instagent import instagent
  File "/home/g0dzila/tools/osint/instagent/app/src/instagent.py", line 12, in <module>
    from instagrapi import Client
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/__init__.py", line 12, in <module>
    from instagrapi.mixins.clip import DownloadClipMixin, UploadClipMixin
  File "/home/g0dzila/tools/osint/instagent/venv/lib/python3.9/site-packages/instagrapi/mixins/clip.py", line 17, in <module>
    raise Exception("You don't have PIL installed. Please install PIL or Pillow>=8.1.1")
Exception: You don't have PIL installed. Please install PIL or Pillow>=8.1.1
```

**Comment by t-abraham** [comment]
Hi I ha

**Comment by ghostkernel-core** [comment]
Hi... I have rechecked and corrected the issues... there were some other issues too apart from the Pillow package... I have solved it and checked it on my pc... It should be good to go now... Please check it out again and if it works you can close down the issue... thank you for pointing out the issues.

**Comment by Rayzen-dev** [comment]
Nice for me with the last pull, you can close this issue. ;)

**Comment by Vettl5** [comment]
> Hello [Rayzen-dev](https://github.com/Rayzen-dev). Thank you for pointing out the issue. It was due to a missing module in the requirements file. I have just now updated the file... You can either re-download the system again and try or just update the requirements.txt file with the latest one and resume from step 5

I've just pulled/installed today and still have the same problem. Any suggestions? ~kali linux, 30.01.23

**Comment by Isaiah0429** [comment]
@Vettl5 

Just found the workaround.

Python3 no longer works properly outside venv due to the most recent update.

Run the main.py after doing these commands from the tutorial

$ python3 -m venv venv
$ source ./venv/bin/activate

Hope this helps!

**Comment by Vettl5** [comment]
> @Vettl5
> 
> Just found the workaround.
> 
> Python3 no longer works properly outside venv due to the most recent update.
> 
> Run the main.py after doing these commands from the tutorial
> 
> $ python3 -m venv venv $ source ./venv/bin/activate
> 
> Hope this helps!

<img width="378" alt="Unbenannt" src="https://github.com/t-abraham/instagent/assets/100218653/08f2c440-4509-495e-8eb9-1e0bd47bc25e">

I can't get behind it, did i miss something? I just cloned the repository today, installed as suggested, initialised the requirements.txt file and opened a virtual environment, put in the credentials and everything. But both ways, opening a instagent prompt / directly setting  the command behind the users name do not work. Need support over here :p

**Comment by ghostkernel-core** [comment]
It seems like the package instagrapi==1.16.30 was not installed when you did the pip install... try installing the pip install instagrapi==1.16.30 in the venv or install the whole requirement.txt in the venv
