### ISSUE TITLE
No module named 'gnureadline'

### ISSUE THREAD

**Issue by Vettl5** [t-abraham/instagent#7]
![image](https://user-images.githubusercontent.com/100218653/215731937-737060f0-51af-4165-9ee3-0da5cbc5e05c.png)

I tried to execute normally as you would do it in any other case. Unfortunately this error appears (line 209). My system is a clean, updated kali linux (31.01.2023).
`ModuleNotFoundError: No module named 'gnureadline'`

I've found this article: https://pypi.org/project/gnureadline/
Maybe helpful for development.

**Comment by ghostkernel-core** [comment]
Thanks for the bug finding. I am looking into and update you once it's solved... ETA 2 days

**Comment by ghostkernel-core** [comment]
@Vettl5 I have updated the requirements file for the support of  `"gnureadline"`. Please repull the repo and try again.

Please confirm me if it works or not and when working, please close the issue. Thank you

**Comment by Vettl5** [comment]
Works like a charm. Thanks for your solid help! 
Quick question: why is the email finder option (fwersemail, fwingsemail), which was originally included in Osintgram, missing? Is it coming in a later release or did you remove it permanently?

**Comment by Vettl5** [comment]
I will close the issue after you answered :)

**Comment by ghostkernel-core** [comment]
Great that it works now.

To answer your question... The features are not removed but integrated into the following commands

`followers`
`followings`

When you run those commands, instead or returning just the emails, it will return your a table of various information about the users.


```
Return for "followers" Command:

"Target's Follower ID", 
"Target's Follower UserName", 
"Target's Follower Name",
"Target's Follower Private Profile",
"Target's Follower Verified", 
"Target's Follower Media Count", 
"Target's Follower Follower Count",
"Target's Follower Following Count",            
"Target's Follower Biography",            
"Target's Follower Email",            
"Target's Follower Phone"
```


```
Return for "followings" Command:

"Target's Following ID", 
"Target's Following UserName", 
"Target's Following Name",
"Target's Following Private Profile",
"Target's Following Verified", 
"Target's Following Media Count", 
"Target's Following Follower Count",
"Target's Following Following Count",            
"Target's Following Biography",            
"Target's Following Email",            
"Target's Following Phone"
```

**Comment by Vettl5** [comment]
> Great that it works now.
> 
> To answer your question... The features are not removed but integrated into the following commands
> 
> `followers` `followings`
> 
> When you run those commands, instead or returning just the emails, it will return your a table of various information about the users.
> 
> ```
> Return for "followers" Command:
> 
> "Target's Follower ID", 
> "Target's Follower UserName", 
> "Target's Follower Name",
> "Target's Follower Private Profile",
> "Target's Follower Verified", 
> "Target's Follower Media Count", 
> "Target's Follower Follower Count",
> "Target's Follower Following Count",            
> "Target's Follower Biography",            
> "Target's Follower Email",            
> "Target's Follower Phone"
> ```
> 
> ```
> Return for "followings" Command:
> 
> "Target's Following ID", 
> "Target's Following UserName", 
> "Target's Following Name",
> "Target's Following Private Profile",
> "Target's Following Verified", 
> "Target's Following Media Count", 
> "Target's Following Follower Count",
> "Target's Following Following Count",            
> "Target's Following Biography",            
> "Target's Following Email",            
> "Target's Following Phone"
> ```

Oh that's interesting! I am sorry for not noticing. I just did not have quiet a chance to test this tool to its fullest. Thanks, for your help, again!
