### ISSUE TITLE
Files for all the commands

### ISSUE THREAD

**Issue by demolayy** [t-abraham/instagent#8]
some commands are not generating flies.
it would be nice to have them also saved
for now, info, detailedfollowers, detailedfollowings does not save anything

thxx

**Comment by ghostkernel-core** [comment]
Thanks for the update... I will look into it and promptly and update you

**Comment by ghostkernel-core** [comment]
Hi i checked into the issue. it should be working. no bugs found. to save files for the command u need to activate the saving mode first using the command 
```
"FILE=y/n"
"JSON=y/n"
```
